name: Manual workflow
on:
  workflow_dispatch:
jobs:
  hurr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: durr
      run: |
        ls
        pwd
        ls SMF2.1
